"""empty message

Revision ID: 5ec2866c12f1
Revises: b6d54b11b1b7
Create Date: 2024-01-23 16:10:38.950441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec2866c12f1'
down_revision = 'b6d54b11b1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user_post_id', sa.Integer(), nullable=True),
    sa.Column('transporter_post_id', sa.Integer(), nullable=True),
    sa.Column('passenger_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_post_id'], ['passengers_table.id'], name=op.f('fk_comments_table_passenger_post_id_passengers_table')),
    sa.ForeignKeyConstraint(['transporter_post_id'], ['transporters_table.id'], name=op.f('fk_comments_table_transporter_post_id_transporters_table')),
    sa.ForeignKeyConstraint(['user_post_id'], ['users_table.id'], name=op.f('fk_comments_table_user_post_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_table')
    # ### end Alembic commands ###
