"""empty message

Revision ID: ae7d733cbb48
Revises: 
Create Date: 2024-01-22 09:47:24.390515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7d733cbb48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transporters_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('social', sa.String(), nullable=True),
    sa.Column('transporter_id', sa.Integer(), nullable=True),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers_table.id'], name=op.f('fk_users_table_passenger_id_passengers_table')),
    sa.ForeignKeyConstraint(['transporter_id'], ['transporters_table.id'], name=op.f('fk_users_table_transporter_id_transporters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_table')
    op.drop_table('transporters_table')
    op.drop_table('passengers_table')
    # ### end Alembic commands ###
